import os
from google import genai
from google.genai import types

def generate_documentation(project_context: str) -> str:
    """
    Sends the full codebase text to Gemini to generate comprehensive documentation.
    """
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key or api_key == "your_api_key_here":
        raise ValueError("GEMINI_API_KEY environment variable is missing or not set securely.")

    client = genai.Client(api_key=api_key)

    system_instruction = """
You are an expert principle software engineer and technical writer. 
Your task is to analyze the provided codebase context and generate comprehensive, highly professional documentation for the project.

CRITICAL INSTRUCTION: Under NO circumstances should you mention that this documentation was generated by AI, an LLM, Gemini, or any automated tool. Present the documentation as if it were written entirely by human developers.

The output MUST be formatted as a single Markdown document with the following sections:
1.  **Project Title** (Infer a good name from the context)
2.  **Overview / Description** (High level summary of what the project does)
3.  **Architecture & Tech Stack** (List the languages, frameworks, and tools used)
4.  **Directory Structure** (A high-level tree representation of the important files)
5.  **Core Components / Modules** (Detailed explanation of key files and what they do)
6.  **Getting Started / Installation** (Steps to run the project, based on what you see in the codebase)
7.  **API Endpoints** (If applicable, list the exposed APIs or functions)

Provide clear, constructive, and accurate documentation. Emphasize readability and clarity without any AI-related disclaimers.
    """

    user_prompt = f"""
Please review the complete source code and structure for the project provided below, and generate comprehensive documentation based on the system instructions.

<project_codebase>
{project_context}
</project_codebase>
    """

    try:
        # Using Gemini 2.5 Flash as default for fast, highly capable massive context reasoning
        response = client.models.generate_content(
            model='gemini-2.5-flash',
            contents=user_prompt,
            config=types.GenerateContentConfig(
                system_instruction=system_instruction,
                temperature=0.2, # Low temperature for more factual, less creative output
            )
        )
        return response.text
    except Exception as e:
        raise Exception(f"Failed to generate documentation via Gemini: {str(e)}")
